apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: my-pvc
spec: 
  storageClassName: standard  #this is default available in local kind cluster
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G