apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-with-usage
spec:
  selector:
    matchLabels:
      app: my-app  
  replicas: 1
  template: 
    metadata: 
      labels:  
        app: my-app 
    spec:
      containers:
      - name: nginx
        image: nginx
        startupProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1
          failureThreshold: 30
        # livenessProbe:
        #   httpGet:
        #     path: /live.html
        #     port: 80
        #   periodSeconds: 1
        #   failureThreshold: 30  
        readinessProbe:
          httpGet:
            path: /  
            port: 80
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests: 
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata: 
  name: demo-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: demo
    image: vinsdocker/util
    args:
    - "sleep"
    - "3600"