apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-with-usage
spec:
  selector:
    matchLabels:
      app: my-app  
  replicas: 3
  template: 
    metadata: 
      labels:  
        app: my-app 
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests: 
            cpu: 1
            memory: 100Mi
          limits:
            cpu: 2
            memory: 500Mi