apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
spec:
  containers:
  - name: nginx-1
    image: nginx
  - name: nginx-2
    image: nginx
#the second container(nginx-2) will fail to run since the my-pod port 80 is already occupied by container nginx-1