apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
spec:
  restartPolicy: OnFailure # Always(by default), Never and OnFailure
  containers:
  - name: ubuntu
    image: ubuntu
    env:  # defining enviornment varibales and passing it as an argument in args at below
    -  name: "request.timeout"
       value: "10ms"
    -  name: "spring.profiles.active"
       value: "dev"
    args:
    -  "env" 