apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client
  annotations:  
    kubernetes.io/change-cause: "deploying v1"
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
  selector:
    matchLabels:
      app: redis-client
  replicas: 1
  template: 
    metadata: 
      labels:  
        app: redis-client
    spec:
      containers:
      - name: redis-client
        image: vinsdocker/k8s-deploy-assignment
        ports:
        - name: "app-port"
          containerPort: 8080
        env:
        - name: "spring.redis.host"
          value: "10.244.2.20"
        - name: "spring.redis.port"
          value: "6379"