apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 2
  template: 
    metadata: 
      labels:  
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vinsdocker/k8s-app:v2
        ports:
        - name: "app-port"
          containerPort: 80