apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-order-service
  annotations:  # for recording the rollout messages, here we are using standard kubernetes.io for same but this can be also customize
    kubernetes.io/change-cause: "deploying v2"
spec:
  minReadySeconds: 10   # custom spring boot apps take time to get running, so minReadySeconds will not make this apps available unless defined wait time.
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: order-service
  replicas: 2
  template: 
    metadata: 
      labels:  
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vinsdocker/k8s-app:v2
        ports:
        - name: "app-port"
          containerPort: 80