apiVersion: v1
kind: Secret
metadata:
  name: mongo-job-secret
data: 
  spring.data.mongodb.uri: bW9uZ29kYjovL2pvYl91c2VyOmpvYl9wYXNzd29yZEBtb25nbzoyNzAxNy9qb2I=
  #"mongodb://job_user:job_password@mongo:27017/job" 
  # for base64 value, run in linux: echo -n <uri-value> | base64
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-candidate-secret
data: 
  spring.data.mongodb.uri: bW9uZ29kYjovL2NhbmRpZGF0ZV91c2VyOmNhbmRpZGF0ZV9wYXNzd29yZEBtb25nbzoyNzAxNy9jYW5kaWRhdGU=
  #"mongodb://candidate_user:candidate_password@mongo:27017/candidate"