apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
spec:
  containers:
  - name: nginx
    image: nginx
    startupProbe:   # for defining probe
      httpGet:
        path: /
        port: 80
      periodSeconds: 10
      failureThreshold: 3