apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
spec:
  containers:
  - name: nginx
    image: nginx
    startupProbe:   # for defining probe
      exec: 
        command:
        - "cat"
        - "/usr/share/nginx/html/index.html"
      periodSeconds: 10
      failureThreshold: 3