apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
spec:
  containers:
  - name: mongo
    image: mongo
    startupProbe:   # for defining probe
      tcpSocket: 
        port: 27017
      periodSeconds: 10
      failureThreshold: 3