# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
- role: control-plane
  extraPortMappings:  # added for enabling node port configuration
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
- role: worker
- role: worker