apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data: 
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=      # base64 value of Rupesh, run in linux: echo -n Rupesh | base64
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=   #admin
---
apiVersion: v1
kind: Secret
metadata:
  name: express-secret
data: 
  ME_CONFIG_MONGODB_ADMINUSERNAME: YWRtaW4=     
  ME_CONFIG_MONGODB_ADMINPASSWORD: cGFzc3dvcmQ= 