apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data: 
  appkey: |
    c3dpc3MuYmFuay5hY2NvdW50OjAwNw0Kc2Vuc2l2aXR5OmNvbmZpZGVudGlhbA0KdXNlcm5hbWU6UnVwZXNoDQpwYXNzd29yZDphZG1pbg==
---
apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    volumeMounts:
    - name: secret-volume1
      mountPath: /usr/share/secret
    args:
    - sleep
    - "3600"  
  volumes:
  - name: secret-volume1
    secret:
      secretName: app-secret