apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data: 
  userName: UnVwZXNo       # base64 value of Rupesh, run in linux: echo -n Rupesh | base64
  password: YWRtaW4xMjM=   # echo -n admin123 | base64       
---
apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    env:
    - name: "app.username"
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: userName
    - name: "app.password"
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: password
    args:
    - env